# Generated by Django 4.1.5 on 2023-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя заказчика')),
                ('mail', models.CharField(max_length=50, verbose_name='почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('place_of_chill', models.CharField(max_length=100, verbose_name='место для отдыха')),
            ],
        ),
    ]
